### ISSUE TITLE
Server Crash with 1.7

### ISSUE THREAD

**Issue by ekiplier** [sanedsf/Hunger-Mechanics#2]
I hope you can get this fixed because I really like the mod, and I was hoping I could provide a server pack for my modpack with it :)
Here's the crash report:
[crash-2021-09-01_14.51.50-fml.txt](https://github.com/sanedsf/Hunger-Mechanics/files/7091628/crash-2021-09-01_14.51.50-fml.txt)

**Comment by sanedsf** [comment]
I thought I fixed that. I will take another look at this.

**Comment by ekiplier** [comment]
Hello! sorry for being persistent, but has there been any breakthrough to fix this issue yet?

**Comment by sanedsf** [comment]
Unfortunately no. I tried to fix it but somehow managed to break my entire workspace. So currently it will remain in an unfinished state until someone comes along and suggests a change or until I have the time to sit down and experiment with it further.

**Comment by ekiplier** [comment]
Hmmm... I could try to contact someone I know who might be able to help given they get access to the source code. This could take some time tho as it would probably involve some form of payment, and I can't afford it atm
